<?php
/**
 * The Template for displaying a single sermon.
 *
 * @package WordPress
 * @subpackage ChurchThemes
 *
 ===================================================================================================
 WARNING! DO NOT EDIT THIS FILE OR ANY TEMPLATE FILES IN THIS THEME!

 To make it easy to update your theme, you should not edit this file. Instead, you should create a
 Child Theme first. This will ensure your template changes are not lost when updating the theme.

 You can learn more about creating Child Themes here: http://codex.wordpress.org/Child_Themes

 You have been warned! :)
 ===================================================================================================
 */

get_header();

global $post;
$args=array(
	'post_type' => 'ct_sermon',
	'post_status' => 'publish',
	'p' => $post->ID,
	'posts_per_page' => 1,
);
$query = null;
$query = new WP_Query($args);

$sermon_speaker = get_the_term_list($post->ID, 'sermon_speaker');
$thespeakers = strip_tags($sermon_speaker);
$sermon_series = get_the_term_list($post->ID, 'sermon_series');
$theseries = strip_tags($sermon_series);
$sermon_service = get_the_term_list($post->ID, 'sermon_service');
//$theservices = strip_tags($sermon_service);
$sermon_topic = get_the_term_list($post->ID, 'sermon_topic');
$thetopics = strip_tags($sermon_topic);

$sm_video_embed = get_post_meta($post->ID, '_ct_sm_video_embed', true);
$sm_video_file = get_post_meta($post->ID, '_ct_sm_video_file', true);


$sm_audio_length = get_post_meta($post->ID, '_ct_sm_audio_length', true);
$sm_audio_file = get_post_meta($post->ID, '_ct_sm_audio_file', true);

$sm_sg_file = get_post_meta($post->ID, '_ct_sm_sg_file', true);

$sm_bible01_book = get_post_meta($post->ID, '_ct_sm_bible01_book', true);
$sm_bible01_start_chap = get_post_meta($post->ID, '_ct_sm_bible01_start_chap', true);
$sm_bible01_start_verse = get_post_meta($post->ID, '_ct_sm_bible01_start_verse', true);
$sm_bible01_end_chap = get_post_meta($post->ID, '_ct_sm_bible01_end_chap', true);
$sm_bible01_end_verse = get_post_meta($post->ID, '_ct_sm_bible01_end_verse', true);

$sm_bible02_book = get_post_meta($post->ID, '_ct_sm_bible02_book', true);
$sm_bible02_start_chap = get_post_meta($post->ID, '_ct_sm_bible02_start_chap', true);
$sm_bible02_start_verse = get_post_meta($post->ID, '_ct_sm_bible02_start_verse', true);
$sm_bible02_end_chap = get_post_meta($post->ID, '_ct_sm_bible02_end_chap', true);
$sm_bible02_end_verse = get_post_meta($post->ID, '_ct_sm_bible02_end_verse', true);

$sm_bible03_book = get_post_meta($post->ID, '_ct_sm_bible03_book', true);
$sm_bible03_start_chap = get_post_meta($post->ID, '_ct_sm_bible03_start_chap', true);
$sm_bible03_start_verse = get_post_meta($post->ID, '_ct_sm_bible03_start_verse', true);
$sm_bible03_end_chap = get_post_meta($post->ID, '_ct_sm_bible03_end_chap', true);
$sm_bible03_end_verse = get_post_meta($post->ID, '_ct_sm_bible03_end_verse', true);

$sm_bible04_book = get_post_meta($post->ID, '_ct_sm_bible04_book', true);
$sm_bible04_start_chap = get_post_meta($post->ID, '_ct_sm_bible04_start_chap', true);
$sm_bible04_start_verse = get_post_meta($post->ID, '_ct_sm_bible04_start_verse', true);
$sm_bible04_end_chap = get_post_meta($post->ID, '_ct_sm_bible04_end_chap', true);
$sm_bible04_end_verse = get_post_meta($post->ID, '_ct_sm_bible04_end_verse', true);

$sm_bible05_book = get_post_meta($post->ID, '_ct_sm_bible05_book', true);
$sm_bible05_start_chap = get_post_meta($post->ID, '_ct_sm_bible05_start_chap', true);
$sm_bible05_start_verse = get_post_meta($post->ID, '_ct_sm_bible05_start_verse', true);
$sm_bible05_end_chap = get_post_meta($post->ID, '_ct_sm_bible05_end_chap', true);
$sm_bible05_end_verse = get_post_meta($post->ID, '_ct_sm_bible05_end_verse', true);

$sermon_settings = get_option('ct_sermon_settings');
isset($sermon_settings['single_layout']) ? $page_layout = $sermon_settings['single_layout'] : $page_layout = null;
isset($sermon_settings['facebook_likes']) ? $facebook_likes = $sermon_settings['facebook_likes'] : $facebook_likes = null;
isset($sermon_settings['tweet_this']) ? $tweet_this = $sermon_settings['tweet_this'] : $tweet_this = null;
isset($sermon_settings['podcast_subscribe_url']) ? $podcast_subscribe_url = $sermon_settings['podcast_subscribe_url'] : $podcast_subscribe_url = null;
isset($sermon_settings['podcast_subscribe_button_text']) ? $podcast_subscribe_button_text = $sermon_settings['podcast_subscribe_button_text'] : $podcast_subscribe_button_text = null;

if(empty($podcast_subscribe_button_text)) $podcast_subscribe_button_text = 'Subscribe to Podcast';

?>
<?php if($query->have_posts()) while($query->have_posts()): $query->the_post(); ?>
		<div class="content-title">
			<?php ct_sermon_meta(); ?>
		</div>
		
		<div class="entry">
            <div <?php post_class('single clear'); ?> id="post_<?php the_ID(); ?>">
                <div class="post-meta">
                    <h1><?php the_title(); ?></h1>
                    from <span
                        class="post-date"><?php the_time(__('M j, Y')) ?></span> <?php edit_post_link( __( 'Edit entry'), '&bull; '); ?></div>
                <div class="post-content">
				<?php if($sm_video_embed): ?>
				
				<div class="video_player">
					
					<?php echo apply_filters( 'the_content', $sm_video_embed ) ?>
				</div>
<?php elseif(has_post_thumbnail()): ?>
				<div class="image"><?php the_post_thumbnail('single'); ?></div>
<?php endif; ?>
<?php if(!empty($sm_audio_file)): ?>
				<div class="audio_player">
						<div class="player"><?php echo do_shortcode("[audio ". $sm_audio_file ."]"); ?></div>
						<p class="audio download"><a href="<?php echo $sm_audio_file ?>" title="right-click to download">Download</a></p>
					</div>
<?php endif; ?>
<div class="action">
<?php if($sm_sg_file): ?>

						<p><a href="<?php echo $sm_sg_file; ?>" class="print download" title="<?php _e('Download','churchthemes'); ?>">Download</a></p>

<?php endif; ?>
<?php if($podcast_subscribe_url): ?>
					<p>
					<a href="<?php echo $podcast_subscribe_url; ?>" class="download podcast" title="<?php echo $podcast_subscribe_button_text; ?>"><?php echo $podcast_subscribe_button_text; ?></a>
					</p>
<?php endif; ?>
</div>

<?php
if ( function_exists( 'sharing_display' ) ) {
    echo sharing_display();
	}
?>
<?php $the_content = get_the_content(); if($the_content): ?>
				<!-- <h3>Summary</h3> -->
				<?php the_content(); ?>
<?php endif; ?>
				</div>

                <div class="post-footer">
                <?php if($sermon_topic): ?>
				<div class="topics">
					<h3>Topics</h3>
					<p><?php echo get_the_term_list($post->ID, 'sermon_topic', '', '&nbsp;&nbsp;&nbsp;&nbsp;'); ?></p>
				</div>
<?php endif; ?>
				<?php if($sm_bible01_book||$sm_bible02_book||$sm_bible03_book||$sm_bible04_book||$sm_bible05_book): ?>
				<div class="bible_refs">
					<h3>Bible References</h3>
					<ul>
						<?php
							$book = $sm_bible01_book;
							$start_chap = $sm_bible01_start_chap;
							$start_verse = $sm_bible01_start_verse;
							$end_chap = $sm_bible01_end_chap;
							$end_verse = $sm_bible01_end_verse;
							
							if(!empty($book)):
								echo '<li>'. $book;
							endif;
							
							if(!empty($start_chap)):
								echo ' '. $start_chap;
							endif;
							
							if(!empty($start_chap) && !empty($start_verse)):
								echo ':'. $start_verse;
							endif;
							
							if(!empty($end_chap) && !empty($end_verse)):
								if($start_chap == $end_chap):
									echo ' - '. $end_verse;
								else:
									echo ' - '. $end_chap .':'. $end_verse;
								endif;
							endif;
							
							if(empty($end_chap) && !empty($end_verse)):
								if(!empty($start_verse)):
									echo ' - '. $end_verse;
								endif;
							endif;
							
							if(!empty($end_chap) && empty($end_verse)):
								if(!empty($start_chap) && empty($start_verse)):
									echo ' - '. $end_chap;
								endif;
							endif;
							
							if(!empty($book)):
								echo '</li>';
							endif;
						?>
						<?php
							$book = $sm_bible02_book;
							$start_chap = $sm_bible02_start_chap;
							$start_verse = $sm_bible02_start_verse;
							$end_chap = $sm_bible02_end_chap;
							$end_verse = $sm_bible02_end_verse;
							
							if(!empty($book)):
								echo '<li>'. $book;
							endif;
							
							if(!empty($start_chap)):
								echo ' '. $start_chap;
							endif;
							
							if(!empty($start_chap) && !empty($start_verse)):
								echo ':'. $start_verse;
							endif;
							
							if(!empty($end_chap) && !empty($end_verse)):
								if($start_chap == $end_chap):
									echo ' - '. $end_verse;
								else:
									echo ' - '. $end_chap .':'. $end_verse;
								endif;
							endif;
							
							if(empty($end_chap) && !empty($end_verse)):
								if(!empty($start_verse)):
									echo ' - '. $end_verse;
								endif;
							endif;
							
							if(!empty($end_chap) && empty($end_verse)):
								if(!empty($start_chap) && empty($start_verse)):
									echo ' - '. $end_chap;
								endif;
							endif;
							
							if(!empty($book)):
								echo '</li>';
							endif;
						?>
						<?php
							$book = $sm_bible03_book;
							$start_chap = $sm_bible03_start_chap;
							$start_verse = $sm_bible03_start_verse;
							$end_chap = $sm_bible03_end_chap;
							$end_verse = $sm_bible03_end_verse;
							
							if(!empty($book)):
								echo '<li>'. $book;
							endif;
							
							if(!empty($start_chap)):
								echo ' '. $start_chap;
							endif;
							
							if(!empty($start_chap) && !empty($start_verse)):
								echo ':'. $start_verse;
							endif;
							
							if(!empty($end_chap) && !empty($end_verse)):
								if($start_chap == $end_chap):
									echo ' - '. $end_verse;
								else:
									echo ' - '. $end_chap .':'. $end_verse;
								endif;
							endif;
							
							if(empty($end_chap) && !empty($end_verse)):
								if(!empty($start_verse)):
									echo ' - '. $end_verse;
								endif;
							endif;
							
							if(!empty($end_chap) && empty($end_verse)):
								if(!empty($start_chap) && empty($start_verse)):
									echo ' - '. $end_chap;
								endif;
							endif;
							
							if(!empty($book)):
								echo '</li>';
							endif;
						?>
						<?php
							$book = $sm_bible04_book;
							$start_chap = $sm_bible04_start_chap;
							$start_verse = $sm_bible04_start_verse;
							$end_chap = $sm_bible04_end_chap;
							$end_verse = $sm_bible04_end_verse;
							
							if(!empty($book)):
								echo '<li>'. $book;
							endif;
							
							if(!empty($start_chap)):
								echo ' '. $start_chap;
							endif;
							
							if(!empty($start_chap) && !empty($start_verse)):
								echo ':'. $start_verse;
							endif;
							
							if(!empty($end_chap) && !empty($end_verse)):
								if($start_chap == $end_chap):
									echo ' - '. $end_verse;
								else:
									echo ' - '. $end_chap .':'. $end_verse;
								endif;
							endif;
							
							if(empty($end_chap) && !empty($end_verse)):
								if(!empty($start_verse)):
									echo ' - '. $end_verse;
								endif;
							endif;
							
							if(!empty($end_chap) && empty($end_verse)):
								if(!empty($start_chap) && empty($start_verse)):
									echo ' - '. $end_chap;
								endif;
							endif;
							
							if(!empty($book)):
								echo '</li>';
							endif;
						?>
						<?php
							$book = $sm_bible05_book;
							$start_chap = $sm_bible05_start_chap;
							$start_verse = $sm_bible05_start_verse;
							$end_chap = $sm_bible05_end_chap;
							$end_verse = $sm_bible05_end_verse;
							
							if(!empty($book)):
								echo '<li>'. $book;
							endif;
							
							if(!empty($start_chap)):
								echo ' '. $start_chap;
							endif;
							
							if(!empty($start_chap) && !empty($start_verse)):
								echo ':'. $start_verse;
							endif;
							
							if(!empty($end_chap) && !empty($end_verse)):
								if($start_chap == $end_chap):
									echo ' - '. $end_verse;
								else:
									echo ' - '. $end_chap .':'. $end_verse;
								endif;
							endif;
							
							if(empty($end_chap) && !empty($end_verse)):
								if(!empty($start_verse)):
									echo ' - '. $end_verse;
								endif;
							endif;
							
							if(!empty($end_chap) && empty($end_verse)):
								if(!empty($start_chap) && empty($start_verse)):
									echo ' - '. $end_chap;
								endif;
							endif;
							
							if(!empty($book)):
								echo '</li>';
							endif;
						?>
					</ul>
				</div>
<?php endif; ?>
				</div> <!-- end footer -->
                        
				
						
            </div>
          

            </div>
		
			




				
				
<?php endwhile; // end of the loop. ?>


<?php get_footer(); ?>